# Generated by Django 4.1.2 on 2022-12-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0003_detail_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='FoodType',
            field=models.CharField(choices=[('Governor Yard', 'Governor Yard'), ('Senator Yard', 'Senator Yard'), ('Monza Yard', 'Monza Yard'), ('Willaim Mark Yard', 'Willaim Mark Yard'), ('Gardo Yard', 'Gardo Yard'), ('Gk Yrad', 'Gk Yrad'), ('Sk Yard', 'Sk Yard'), ('Het Yard', 'Het Yard'), ('Starrose Yard', 'Starrose Yard'), ('Plain merino Yrad', 'Plain merino Yrad')], max_length=30),
        ),
    ]
