# Generated by Django 4.1.2 on 2022-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0005_remove_detail_foodtype_detail_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Reg_No',
            field=models.CharField(choices=[('CST/18/IFT/00125', 'CST/18/IFT/00125'), ('CST/18/IFT/00119', 'CST/18/IFT/00119'), ('CST/18/IFT/00118', 'CST/18/IFT/00118'), ('CST/18/IFT/00107', 'CST/18/IFT/00107'), ('CST/18/IFT/00101', 'CST/18/IFT/00101'), ('CST/18/IFT/00109', 'CST/18/IFT/00109'), ('CST/18/IFT/00140', 'CST/18/IFT/00140')], max_length=30),
        ),
    ]
